version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Chat-System
      MYSQL_USER: chat
      MYSQL_PASSWORD: chat
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
